@startuml
interface IPerDiemA {
    getValue()
}

class PerDiemAStayFirst {
    BaseFee
    CheckOutTime
    getValue()
}

class PerDiemAStay {
    BaseFee
    getValue()
}

class PerDiemAStayLast {
    BaseFee
    CheckOutTime
    getValue()
}

class PerDiemADayTrip {
    BaseFee
    CheckOutTime
    getValue()
}

class CheckOutTime {
    StartTime
    EndTime
    calc()
}

class StartTime {
    Location
    Time
    getTime()
}

class EndTime {
    Location
    Time
    getTime()
}

class Location {
    address
    isHome
}

class BaseFee {
    Capacity
    getBaseFee()
}

class FeeA {
    CheckoutTime
    Date
    Capacity
}

IPerDiemA <|.. PerDiemAStayFirst
IPerDiemA <|.. PerDiemAStayMiddle
IPerDiemA <|.. PerDiemAStayLast
IPerDiemA <|.. PerDiemADayTrip
@enduml